# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QTabWidget, QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 592)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionOpen.setIcon(icon)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon1 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.actionSave_As.setIcon(icon1)
        self.actionImportAudio = QAction(MainWindow)
        self.actionImportAudio.setObjectName(u"actionImportAudio")
        icon2 = QIcon(QIcon.fromTheme(u"audio-card"))
        self.actionImportAudio.setIcon(icon2)
        self.actionImportPDF = QAction(MainWindow)
        self.actionImportPDF.setObjectName(u"actionImportPDF")
        icon3 = QIcon(QIcon.fromTheme(u"accessories-dictionary"))
        self.actionImportPDF.setIcon(icon3)
        self.actionFullscreen = QAction(MainWindow)
        self.actionFullscreen.setObjectName(u"actionFullscreen")
        self.actionFullscreen.setCheckable(True)
        icon4 = QIcon(QIcon.fromTheme(u"view-fullscreen"))
        self.actionFullscreen.setIcon(icon4)
        self.actionPlay = QAction(MainWindow)
        self.actionPlay.setObjectName(u"actionPlay")
        icon5 = QIcon(QIcon.fromTheme(u"media-playback-start"))
        self.actionPlay.setIcon(icon5)
        self.actionPlay.setMenuRole(QAction.MenuRole.NoRole)
        self.actionNext_Practice_Marker = QAction(MainWindow)
        self.actionNext_Practice_Marker.setObjectName(u"actionNext_Practice_Marker")
        icon6 = QIcon(QIcon.fromTheme(u"media-seek-forward"))
        self.actionNext_Practice_Marker.setIcon(icon6)
        self.actionNext_Practice_Marker.setMenuRole(QAction.MenuRole.NoRole)
        self.actionPrevious_Practice_Marker = QAction(MainWindow)
        self.actionPrevious_Practice_Marker.setObjectName(u"actionPrevious_Practice_Marker")
        icon7 = QIcon(QIcon.fromTheme(u"media-seek-backward"))
        self.actionPrevious_Practice_Marker.setIcon(icon7)
        self.actionPrevious_Practice_Marker.setMenuRole(QAction.MenuRole.NoRole)
        self.actionNext_Page = QAction(MainWindow)
        self.actionNext_Page.setObjectName(u"actionNext_Page")
        icon8 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.actionNext_Page.setIcon(icon8)
        self.actionNext_Page.setMenuRole(QAction.MenuRole.NoRole)
        self.actionPrevious_Page = QAction(MainWindow)
        self.actionPrevious_Page.setObjectName(u"actionPrevious_Page")
        icon9 = QIcon(QIcon.fromTheme(u"edit-undo"))
        self.actionPrevious_Page.setIcon(icon9)
        self.actionPrevious_Page.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon10 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSave.setIcon(icon10)
        self.actionSave.setMenuRole(QAction.MenuRole.NoRole)
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        icon11 = QIcon(QIcon.fromTheme(u"media-playback-stop"))
        self.actionStop.setIcon(icon11)
        self.actionStop.setMenuRole(QAction.MenuRole.NoRole)
        self.actionExit_Fullscreen = QAction(MainWindow)
        self.actionExit_Fullscreen.setObjectName(u"actionExit_Fullscreen")
        icon12 = QIcon(QIcon.fromTheme(u"go-down"))
        self.actionExit_Fullscreen.setIcon(icon12)
        self.actionExit_Fullscreen.setMenuRole(QAction.MenuRole.NoRole)
        self.actionNew_Project = QAction(MainWindow)
        self.actionNew_Project.setObjectName(u"actionNew_Project")
        icon13 = QIcon(QIcon.fromTheme(u"document-new"))
        self.actionNew_Project.setIcon(icon13)
        self.actionDelete_All_Markers = QAction(MainWindow)
        self.actionDelete_All_Markers.setObjectName(u"actionDelete_All_Markers")
        icon14 = QIcon(QIcon.fromTheme(u"user-trash"))
        self.actionDelete_All_Markers.setIcon(icon14)
        self.actionDelete_Previous_Practice_Marker = QAction(MainWindow)
        self.actionDelete_Previous_Practice_Marker.setObjectName(u"actionDelete_Previous_Practice_Marker")
        self.actionDelete_Next_Practice_Marker = QAction(MainWindow)
        self.actionDelete_Next_Practice_Marker.setObjectName(u"actionDelete_Next_Practice_Marker")
        self.actionDelete_Previous_Page_Marker = QAction(MainWindow)
        self.actionDelete_Previous_Page_Marker.setObjectName(u"actionDelete_Previous_Page_Marker")
        self.actionDelete_Next_Page_Marker = QAction(MainWindow)
        self.actionDelete_Next_Page_Marker.setObjectName(u"actionDelete_Next_Page_Marker")
        self.actionAdd_Page_Marker = QAction(MainWindow)
        self.actionAdd_Page_Marker.setObjectName(u"actionAdd_Page_Marker")
        icon15 = QIcon(QIcon.fromTheme(u"media-flash"))
        self.actionAdd_Page_Marker.setIcon(icon15)
        self.actionAdd_Page_Marker.setMenuRole(QAction.MenuRole.NoRole)
        self.actionAdd_Practice_Marker = QAction(MainWindow)
        self.actionAdd_Practice_Marker.setObjectName(u"actionAdd_Practice_Marker")
        icon16 = QIcon(QIcon.fromTheme(u"appointment-new"))
        self.actionAdd_Practice_Marker.setIcon(icon16)
        self.actionAdd_Practice_Marker.setMenuRole(QAction.MenuRole.NoRole)
        self.actionProject_Options = QAction(MainWindow)
        self.actionProject_Options.setObjectName(u"actionProject_Options")
        icon17 = QIcon(QIcon.fromTheme(u"applications-development"))
        self.actionProject_Options.setIcon(icon17)
        self.actionProject_Options.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMovable(False)
        self.audio_tab = QWidget()
        self.audio_tab.setObjectName(u"audio_tab")
        self.horizontalLayout = QHBoxLayout(self.audio_tab)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget.addTab(self.audio_tab, "")
        self.pdf_tab = QWidget()
        self.pdf_tab.setObjectName(u"pdf_tab")
        self.gridLayout_3 = QGridLayout(self.pdf_tab)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")

        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.tabWidget.addTab(self.pdf_tab, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOption = QMenu(self.menubar)
        self.menuOption.setObjectName(u"menuOption")
        self.menuImport = QMenu(self.menubar)
        self.menuImport.setObjectName(u"menuImport")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuDelete_Practice_Marker = QMenu(self.menuEdit)
        self.menuDelete_Practice_Marker.setObjectName(u"menuDelete_Practice_Marker")
        self.menuDelete_Page_Blue_Marker = QMenu(self.menuEdit)
        self.menuDelete_Page_Blue_Marker.setObjectName(u"menuDelete_Page_Blue_Marker")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(30, 30))
        self.toolBar.setFloatable(True)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuOption.addAction(self.actionProject_Options)
        self.menuOption.addAction(self.actionFullscreen)
        self.menuOption.addSeparator()
        self.menuImport.addAction(self.actionImportPDF)
        self.menuImport.addAction(self.actionImportAudio)
        self.menuEdit.addAction(self.actionAdd_Page_Marker)
        self.menuEdit.addAction(self.actionAdd_Practice_Marker)
        self.menuEdit.addAction(self.menuDelete_Page_Blue_Marker.menuAction())
        self.menuEdit.addAction(self.menuDelete_Practice_Marker.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete_All_Markers)
        self.menuDelete_Practice_Marker.addAction(self.actionDelete_Previous_Practice_Marker)
        self.menuDelete_Practice_Marker.addAction(self.actionDelete_Next_Practice_Marker)
        self.menuDelete_Page_Blue_Marker.addAction(self.actionDelete_Previous_Page_Marker)
        self.menuDelete_Page_Blue_Marker.addAction(self.actionDelete_Next_Page_Marker)
        self.toolBar.addAction(self.actionNew_Project)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImportPDF)
        self.toolBar.addAction(self.actionImportAudio)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious_Practice_Marker)
        self.toolBar.addAction(self.actionAdd_Practice_Marker)
        self.toolBar.addAction(self.actionNext_Practice_Marker)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious_Page)
        self.toolBar.addAction(self.actionAdd_Page_Marker)
        self.toolBar.addAction(self.actionNext_Page)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PDF Player", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open Project [Ctrl+O]", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As [Ctrl+Shift+S]", None))
        self.actionSave_As.setIconText(QCoreApplication.translate("MainWindow", u"Save As [Ctrl+Shift+S]", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("MainWindow", u"Save As [Ctrl+Shift+S]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionImportAudio.setText(QCoreApplication.translate("MainWindow", u"Import Audio [Ctrl+K]", None))
#if QT_CONFIG(tooltip)
        self.actionImportAudio.setToolTip(QCoreApplication.translate("MainWindow", u"Import Audio [Ctrl+K]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionImportAudio.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+K", None))
#endif // QT_CONFIG(shortcut)
        self.actionImportPDF.setText(QCoreApplication.translate("MainWindow", u"Import PDF [Ctrl+I]", None))
#if QT_CONFIG(tooltip)
        self.actionImportPDF.setToolTip(QCoreApplication.translate("MainWindow", u"Import PDF", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionImportPDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionFullscreen.setText(QCoreApplication.translate("MainWindow", u"Fullscreen [F]", None))
#if QT_CONFIG(tooltip)
        self.actionFullscreen.setToolTip(QCoreApplication.translate("MainWindow", u"Fullscreen [F]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFullscreen.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlay.setText(QCoreApplication.translate("MainWindow", u"Play [Spacebar]", None))
#if QT_CONFIG(shortcut)
        self.actionPlay.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_Practice_Marker.setText(QCoreApplication.translate("MainWindow", u"Next Practice Marker [Right Arrow]", None))
#if QT_CONFIG(tooltip)
        self.actionNext_Practice_Marker.setToolTip(QCoreApplication.translate("MainWindow", u"Next Practice Marker [Right Arrow]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNext_Practice_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious_Practice_Marker.setText(QCoreApplication.translate("MainWindow", u"Previous Marker [Left Arrow]", None))
#if QT_CONFIG(tooltip)
        self.actionPrevious_Practice_Marker.setToolTip(QCoreApplication.translate("MainWindow", u"Previous Marker [Left Arrow]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPrevious_Practice_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_Page.setText(QCoreApplication.translate("MainWindow", u"Next Page [Up Arrow]", None))
#if QT_CONFIG(tooltip)
        self.actionNext_Page.setToolTip(QCoreApplication.translate("MainWindow", u"Next Page [Up Arrow]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNext_Page.setShortcut(QCoreApplication.translate("MainWindow", u"Up", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious_Page.setText(QCoreApplication.translate("MainWindow", u"Previous Page [Down Arrow]", None))
#if QT_CONFIG(tooltip)
        self.actionPrevious_Page.setToolTip(QCoreApplication.translate("MainWindow", u"Previous Page [Down Arrow]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPrevious_Page.setShortcut(QCoreApplication.translate("MainWindow", u"Down", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save Project [Ctrl+S]", None))
        self.actionSave.setIconText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save Project [Ctrl+S]", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
#if QT_CONFIG(tooltip)
        self.actionStop.setToolTip(QCoreApplication.translate("MainWindow", u"Stop", None))
#endif // QT_CONFIG(tooltip)
        self.actionExit_Fullscreen.setText(QCoreApplication.translate("MainWindow", u"Minimize", None))
#if QT_CONFIG(tooltip)
        self.actionExit_Fullscreen.setToolTip(QCoreApplication.translate("MainWindow", u"Exit Fullscreen", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExit_Fullscreen.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Project.setText(QCoreApplication.translate("MainWindow", u"New Project [Ctrl+F]", None))
        self.actionDelete_All_Markers.setText(QCoreApplication.translate("MainWindow", u"Delete All Markers [Shift+Del]", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_All_Markers.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Previous_Practice_Marker.setText(QCoreApplication.translate("MainWindow", u"Previous Marker [Alt+Left Arrow]", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Previous_Practice_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Left", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Next_Practice_Marker.setText(QCoreApplication.translate("MainWindow", u"Next Marker [Alt+Right Arrow]", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Next_Practice_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Right", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Previous_Page_Marker.setText(QCoreApplication.translate("MainWindow", u"Previous Page Marker [Alt+Down]", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Previous_Page_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Down", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Next_Page_Marker.setText(QCoreApplication.translate("MainWindow", u"Next Page Marker [Alt+Up]", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Next_Page_Marker.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Up", None))
#endif // QT_CONFIG(shortcut)
        self.actionAdd_Page_Marker.setText(QCoreApplication.translate("MainWindow", u"Add Page Marker", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_Page_Marker.setToolTip(QCoreApplication.translate("MainWindow", u"Add Page Marker", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_Practice_Marker.setText(QCoreApplication.translate("MainWindow", u"Add Practice Marker", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_Practice_Marker.setToolTip(QCoreApplication.translate("MainWindow", u"Add Practice Marker", None))
#endif // QT_CONFIG(tooltip)
        self.actionProject_Options.setText(QCoreApplication.translate("MainWindow", u"Project Options", None))
#if QT_CONFIG(tooltip)
        self.actionProject_Options.setToolTip(QCoreApplication.translate("MainWindow", u"Modify the Project settings", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audio_tab), QCoreApplication.translate("MainWindow", u"Audio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pdf_tab), QCoreApplication.translate("MainWindow", u"PDF", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOption.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuImport.setTitle(QCoreApplication.translate("MainWindow", u"Import", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuDelete_Practice_Marker.setTitle(QCoreApplication.translate("MainWindow", u"Delete Practice (Red) Marker", None))
        self.menuDelete_Page_Blue_Marker.setTitle(QCoreApplication.translate("MainWindow", u"Delete Page (Blue) Marker", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

